# Generated by Django 6.1.1 on 2026-10-04 20:13

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="produto",
            options={"ordering": ["-ativo", "nome"]},
        ),
        migrations.AlterField(
            model_name="itemvenda",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="venda",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddConstraint(
            model_name="produto",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("nome"),
                condition=models.Q(("ativo", True)),
                name="produto_nome_unico_entre_ativos",
            ),
        ),
    ]
