# Generated by Django 6.1.1 on 2026-10-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0002_produto_nome_unico"),
    ]

    operations = [
        migrations.AddField(
            model_name="venda",
            name="cancelada_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="venda",
            name="motivo_cancelamento",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="venda",
            name="situacao",
            field=models.CharField(
                choices=[("Confirmada", "Confirmada"), ("Cancelada", "Cancelada")],
                default="Confirmada",
                max_length=10,
            ),
        ),
    ]
